### ISSUE TITLE
META: Selection subscription API

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/graphistry-releases#144]
Expose single/multi-selection events to parent frame

- [x] Internal implementation: Index translation, ... https://github.com/graphistry/graphistry/issues/1861
- [x] Performance optimization: Pay-as-you-go (global) https://github.com/graphistry/graphistry/issues/1862
- [x] Performance optimization: Client/server caching https://github.com/graphistry/graphistry/issues/1863
- [x] Enrichment with ID, labels
- [x] https://github.com/graphistry/graphistry-js/issues/109
- [x] https://github.com/graphistry/graphistry-js/issues/108
- [x] https://github.com/graphistry/graphistry/issues/1860
- [ ] https://github.com/graphistry/graphistry/issues/1866
- [ ] https://github.com/graphistry/graphistry-js/issues/113
- [ ] (TBD: Bugs!)
