### ISSUE TITLE
META: Highlight & Selection write API - prototype

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/graphistry-releases#145]
Enable embedding users to trigger fast highlights & selections of items

Ex:
* User hovers over a name or group ID in outside tool
* Outside tool identifies corresponding node & edge IDs of interest
* Graphistry UI highlights those specific nodes/edges
* User clicks the name or group ID in outside tool
* Graphistry UI selection focuses on those (sticky)
* User clicks filter/exclude/... or other action for interacting with that selected subset
* If user didn't click, but instead mouse-out'd, up to UI to return Highlight state to empty

Out-of-scope: Prototype will -
* Work on internal entity Index, not ID, for PR. Index is the most recent index returned by the selection API.
* Only highlight/select the exact

Piggybacks on selection API work

- [x] design
- [x] client API - https://github.com/graphistry/graphistry-js/issues/111
- [x] internal API - https://github.com/graphistry/graphistry-js/issues/110
- [x] perf check - https://github.com/graphistry/graphistry/issues/1860 (shared)
- [ ] docs & demo - https://github.com/graphistry/graphistry-js/issues/112
- [ ] publish https://github.com/graphistry/graphistry/issues/1866
- [ ] (TBD Bugs)

**Comment by exrhizo** [comment]
Bugs are:
 - When you inject a selection it causes a bunch of events, as many as 10.

 - When you inject a selection, the onSelectionUpdate can have the wrong selection.labels

 - hovering over the nodes to get thier label causes the above to fix it also causes the onSelection to flicker

These didn't reproduce for me with `./nc`

**Comment by lmeyerov** [comment]
What does "hovering over the nodes to get thier label causes the above to fix it" mean?  That the wrong label is shown, and hovering triggers an update that will show the correct one? I wonder if that means we're properly invalidating the label cache, but not subscribing to the invalidations properly in the labels container / triggering the wrong rendering effects for the rendering scheduler?

**Comment by lmeyerov** [comment]
I was actually more worried about filter states messing up local vs global indexing, so the above feels more doable :)

**Comment by lmeyerov** [comment]
@exrhizo  I lost track, can you share status here?

**Comment by lmeyerov** [comment]
(I think this one is paused pending Gadi's feedback)
