### ISSUE TITLE
META: Animated timebar

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/graphistry-releases#146]
Phase 1:

- [x] Design & reviews - Figmas, interviews, etc
- [ ]  Static UI prototype
- [ ]  Opt-in UI mode
- [ ]  Forward-play
- [ ]  Looping - control & UI
- [ ]  Pause/stop/fastforward/...
- [ ]  Bar width control

Not in scope:
- Record control: Analysts can use normal browser tools to screencap - loom, grain, ...
- ? (See Figma)

**Comment by lmeyerov** [comment]
@exrhizo I just sketched one potential breakdown of your work here, can you iterate? I can split up into tickets etc after

**Comment by lmeyerov** [comment]
I think we're coming back to this one probably closer to June
