### ISSUE TITLE
META: multi-node streamgl-viz

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/graphistry-releases#147]
- [ ] https://github.com/graphistry/graphistry-helm/issues/36
- [ ] https://github.com/graphistry/graphistry-helm/issues/35 (we need designs to align)
- [ ] k8s impl
- [ ] cloud native impl (we need impls to align)
